### ISSUE TITLE
How about same plugin for textile?

### ISSUE THREAD

**Issue by pentago** [joeybaker/my_sublime_packages#1]
Hi, any chance you could make similar plugin for textile?

**Comment by joeybaker** [comment]
I don't actually make any of these plugins. I also don't use textile, so I'd not be comfortable recommending a plugin. But, there is a textile plugin built into ST2 that should do the trick. If not, take a look here: http://wbond.net/sublime_packages/community

**Comment by pentago** [comment]
What do you mean by "textile plugin built into ST2"? Could you explain please?

**Comment by joeybaker** [comment]
These are packages for Sublime Text 2 (ST2). There's a textile plugin built in to the program.

**Comment by pentago** [comment]
That's not really a plugin, it just highlights Textile syntax. It doesn't export HTML out of it.And those packages you're referring to don't do what i need at all. Thanks for your time anyways.

**Comment by pentago** [comment]
In fact, i just figured that OmniMarkupPreviewer can preview/export Textile and could use custom templates. It's far more awesome than previous plugin i've been using. Thanks for guiding me to right direction! 

Cheers mate

**Comment by joeybaker** [comment]
Cool. Glad it worked out.
