### ISSUE TITLE
recording a macro with markdown to clipboard doesn't work in sublime text

### ISSUE THREAD

**Issue by ghost** [joeybaker/my_sublime_packages#2]
i tried to record the following macro in sublime text 2:
1. copy markdown as html
2. paste

but the macro doesn't record the first step. the macro produces the following file:
[
    {
        "args": null,
        "command": "paste"
    }
]

**Comment by joeybaker** [comment]
@asensoy I'm not sure which plugin you're using, but you should post an issue in that plugin's repo. I don't author any of these plugins (just collect them and configure them), so I can't help you.
